### ISSUE TITLE
Clarify Silent renewing of access tokens is not supported by all social identity providers.

### ISSUE THREAD

**Issue by spottedmahn** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#17]
Can you please clarify:

>Silent renewing of access tokens is not supported by all social identity providers.

from the [readme.md](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/blob/master/README.md)?

- What IDPs are not supported?
- Why wouldn't they be supported?  We're requesting access tokens B2C not the IDP.
- Is "silent renewing of access tokens" the same thing as ["silently requesting an access token"](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens#requesting-a-token)?

---

Reference: Update docs page request: [Limited Aquire Token Silent Support?](https://github.com/MicrosoftDocs/azure-docs/issues/7531)

**Comment by jennyf19** [comment]
@spottedmahn I'm not aware of this restriction. 

@DarylThayil @sameerag - do you know what the above comment refers to?

cc: @valnav

**Comment by sameerag** [comment]
@ktsakas FYI

**Comment by CodyMorris** [comment]
Any update here?  I see the reference issue has been closed.  Trying to troubleshoot challenges using silent renewal and i'm not sure if its related to these unspecified limitations

**Comment by jennyf19** [comment]
@sameerag @DarylThayil can provide some insight here? thanks

**Comment by sameerag** [comment]
I can add what we support in `msal js` and (@valnav) to correct me if I am missing any information: 

- `msal js` does support B2C flows for `acquireTokenSilent` but with certain conditions due to the manner in which B2C policies can manifest certain UI patterns.
- An interaction is mandated for any initial login and once a session is established and a token can be acquired silently, the use case is straight forward and supported.
- Some policies like `edit-profile` by default would need interaction and calling `acquireTokenSilent` which renders a hidden iframe is blocked by the B2C service with `x-frame-options` set to `deny`

We did some testing with our sample and have generated the below table:

|         *Policy*         |           *Status with Sample*          | *acquireTokenSilent* |
|:------------------------:|:---------------------------------------:|---------------------:|
| SignupSignIn (SUSI) - V2 |            works as expected            |       Supported      |
|    Password Reset - V2   |           X-frame-options deny          |     Not supported    |
|        SignIn - V2       |            works as expected            |       Supported      |
|       Profile Edit       |           X-frame-options deny          |     Not supported    |
|        SignUp - V2       | works as expected for interactive calls |     Not supported    |

It is possible that some IDPs are being called for silent calls where interaction is needed and B2C service is blocking the frame. We are investigating to improve this experience and throw proper errors for now but the above table can be used as a reference as we stabilize B2C experience in our samples for all policies.

Hope this helps.

**Comment by sameerag** [comment]
Also cc @ktsakas is he has anything to add.

**Comment by derisen** [comment]
Closing this due inactivity. Refer to [this post](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/issues/49) for details.
