### ISSUE TITLE
This application does not have sufficient permissions against this web resource

### ISSUE THREAD

**Issue by thdotnet** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#4]
I've downloaded the sample and replaced with my settings. After that, in the web page I'm getting:

Refused to display .... in a frame because it set 'X-Frame-Options' to 'deny'.

If I try to open the url, I'm getting:

This application does not have sufficient permissions against this web resource to perform the operation.

Any tips?

**Comment by parakhj** [comment]
Azure AD B2C does not support authentication in IFrames. For the other issue, see https://github.com/Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp/issues/16

**Comment by thdotnet** [comment]
I was only trying to run the sample. The acquireToken process is the problem.

**Comment by spottedmahn** [comment]
Hi @parakhj I'm having the same problem.  Can you please re-open this?

I first started with running the demo **w/o** any changes and it **worked fine**.

- I then customized the sample for my tenant, scope, etc.
- I downloaded the [web api](https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi) sample app, customized it for my tenant and ran it locally

![image](https://user-images.githubusercontent.com/14079228/27995569-bc46c942-649e-11e7-8687-ae5a7ddf2f14.png)


Here's what happens when I try to login:

![image](https://user-images.githubusercontent.com/14079228/27995547-441b60d6-649e-11e7-98bf-0461f56f7be1.png)

I click login and it brings up the pop-up.  So far so good.

![image](https://user-images.githubusercontent.com/14079228/27995548-46ced9e8-649e-11e7-94f5-341e78bb6171.png)

I successfully login but then I get this console error and the login window again

> Refused to display 'https://login.microsoftonline.com/te/spottedmahnb2c.onmicrosoft.com/b2c_1_s…-423f-90fc-d9a30e5dc7ea-b2c_1_sign-up_or_sign-in&domain_hint=organizations' in a frame because it set 'X-Frame-Options' to 'deny'.

**Comment by spottedmahn** [comment]
I found this [similar issue](https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/94) but I think it is for adal.js, right?

**Comment by thdotnet** [comment]
Hi @spottedmahn, you're right. I had the same issue. The problem happens when you try to call acquireTokenSilent after logged in.

**Comment by spottedmahn** [comment]
@jmprieur any ideas?  thanks!

**Comment by spottedmahn** [comment]
The last webrequest in Chrome was the request to authorize.  It fails when pointed at my tenant.

![image](https://user-images.githubusercontent.com/14079228/28035494-cf468390-6582-11e7-9ef6-6b194a788e45.png)

I pulled the following from **Fiddler**

> GET /te/spottedmahnb2c.onmicrosoft.com/b2c_1_sign-up_or_sign-in/oauth2/v2.0/**authorize**?response_type=token&scope=https%3A%2F%2Fspottedmahnb2c.onmicrosoft.com%2Fb2c-test-1%2Fdemo.read%20openid%20profile&client_id=d0a1dacb-a76f-4cd3-8055-d387a7d821ca&redirect_uri=http%3A%2F%2Flocalhost%3A6421%2F&state=131ccbcd-cffc-41ed-be98-e1eca87349dc&nonce=92203ca0-843c-46e3-8e6e-d7345c99198c&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.1.1&client-request-id=1d34e02b-efc4-4cf9-9d48-5946e519bdfe&prompt=none&domain_req=80033dfd-6eab-42c4-bdf2-4e223d4b396f&login_req=a80a99a7-b018-423f-90fc-d9a30e5dc7ea-b2c_1_sign-up_or_sign-in&domain_hint=organizations HTTP/1.1

### First part of the response ###
<html lang="en-US"><head><link rel="icon" href="data:;base64,iVBORw0KGgo=">
<script data-container="true" nonce="xQ0y7iFPdlesa8vVLcXTuQ==">var GLOBALEX = {"CorrelationId":"99ff48e6-646f-4cc0-bd37-a390093f7a03","Timestamp":"2017-07-10 17:31:40Z","Detail":"AADB2C90205: This application does not have sufficient permissions against this web resource to perform the operation."};

### Full Response ###
[azure ad b2c - spa - failure.txt](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/files/1136758/azure.ad.b2c.-.spa.-.failure.txt)

### This application does not have sufficient permissions against this web resource to perform the operation ###
What application?  My Azure web app?  The web app defined in step 5 of the readme?  Against which web resource?

**Comment by spottedmahn** [comment]
# Permissions Review #

From what I see, the web app, has permissions for the web api scope of demo.read

### Web App Properties ###
![image](https://user-images.githubusercontent.com/14079228/28037026-0f16ad2e-6588-11e7-98c2-8b020acd0c1c.png)

### Web App API Access ###
![image](https://user-images.githubusercontent.com/14079228/28037040-1be2ef72-6588-11e7-8d9b-0b7d49f4da12.png)

### Web API Properties ###

![image](https://user-images.githubusercontent.com/14079228/28037079-37fb73c8-6588-11e7-91d2-71407053104e.png)

### Authorize Request ###

![image](https://user-images.githubusercontent.com/14079228/28037129-695446f2-6588-11e7-889d-06241bae5b67.png)

*Note: I switched api id uri on the web api between this post and my last one as an experiment.

**Comment by spottedmahn** [comment]
I tried the 'run policy settings' and it worked.   I noticed a **difference** in the **scope**.  Through msal.js it has 'demo.read openid profile' vs 'demo.read'.

I see an openid scope but not a profile scope.  Does that have anything to do with my problem?

![image](https://user-images.githubusercontent.com/14079228/28037945-2dd47f2c-658b-11e7-9ceb-8aba40bb3a99.png)

### Run Policy Settings ###

![image](https://user-images.githubusercontent.com/14079228/28037966-409d37e8-658b-11e7-9e84-8f4560e1a612.png)


### Access Token Granted ###

![image](https://user-images.githubusercontent.com/14079228/28037980-511270ca-658b-11e7-996e-b1c91f024ff0.png)

### Query String for Run Policy Settings ###
![image](https://user-images.githubusercontent.com/14079228/28038002-5ff6052a-658b-11e7-8a22-a1097675ed15.png)


### Query String for my demo app using MSAL.js ###
![image](https://user-images.githubusercontent.com/14079228/28038023-6f1dc38a-658b-11e7-8cf9-587b8caed72e.png)

**Comment by parakhj** [comment]
@spottedmahn try adding id_token to the response_type. If you include openid in the scope, then you are requesting an id_token as well, and that has to match the response_type (token represents access token, id_token represents an id token)

For more reference, check out this post: https://github.com/Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp/issues/16

**Comment by spottedmahn** [comment]
@parakhj I reviewed the blog post about setting the permissions.  I think I have them as described in the post.  I've also included them in the screenshots above.  Do you see anything that is not configured properly?

This is the essential the same info on docs.microsoft.com.

Thanks for your assistance here!

**Comment by parakhj** [comment]
Did you add id_token to the response type? (I edited my earlier post)

**Comment by spottedmahn** [comment]
I see your edit, thanks!

I'm not sure how I would do that.  Isn't that something that msal.js is doing for me?

Here's the query string for reference for what is getting sent:

![image](https://user-images.githubusercontent.com/14079228/28044550-04291bc2-65a6-11e7-8177-85427dbd09ba.png)

**Comment by spottedmahn** [comment]
and comparing that to the demo that works, response_type is 'token'

![image](https://user-images.githubusercontent.com/14079228/28044571-29b3923c-65a6-11e7-8997-fdacfb015bda.png)

**Comment by parakhj** [comment]
Given your last two screenshots, we can rule out MSAL and the app as the problem since the sample works with the default configuration, i would focus your debugging on the set up in the portal.

Could you send a screenshot of the API app registration, its published scopes, your native app registration, and its granted scopes?

**Comment by spottedmahn** [comment]
@parakhj thanks for the reply.  Here's my setup:

## Web API Properties/Registration ##
![image](https://user-images.githubusercontent.com/14079228/28119809-19f91f3a-66e4-11e7-8ba3-f4284931cf0b.png)

## Web API Published Scopes ##
![image](https://user-images.githubusercontent.com/14079228/28119817-2211a052-66e4-11e7-8845-58b26717ef29.png)

## Web App Properties/Registration ##
![image](https://user-images.githubusercontent.com/14079228/28119838-3cf643dc-66e4-11e7-9677-9b89cd328ce1.png)

## Web App Granted Scopes ##
![image](https://user-images.githubusercontent.com/14079228/28119866-516a612c-66e4-11e7-8807-feee9bd195ed.png)

**Comment by parakhj** [comment]
Ah! You should be using the scope value in your request, not the scope name

**Comment by spottedmahn** [comment]
That was it, thanks Parakh!

![image](https://user-images.githubusercontent.com/14079228/28137809-916cc430-671c-11e7-8708-4d1b8866b2a3.png)

**Comment by SaeedAkhter-MSFT** [comment]
@thdotnet can you confirm whether you are using the scope value? (using the scope name will not work)  If you are still having an issue I could schedule a short phone call to see if I can help unblock you.

**Comment by thdotnet** [comment]
I'll try. Just to remind, I was able to authenticate users. My problem happened when I was trying to acquire the token using acquireTokenSilent method.

**Comment by SaeedAkhter-MSFT** [comment]
Ok, so might be a slightly different problem, but from your earlier post it looks like you are getting the same error: "AADB2C90205: This application does not have sufficient permissions against this web resource to perform the operation"

Could you post screenshots of the API app registration, its published scopes, your native app registration, and its granted scopes?  (just like the post from spottedmahn above)

**Comment by thdotnet** [comment]
Sure. I'm not working on that task anymore, but I'll do some tests on weekend and update in here.

**Comment by huizarmx** [comment]
Hi @SaeedAkhter-MSFT

Today I experienced the same issue and I have double checked my configuration in the portal and everything seems to be correct.

I'm just running the sample app with the customization of the parameters

![image](https://user-images.githubusercontent.com/10178745/31847871-ecdac3d2-b5e9-11e7-8171-9636fe65feb3.png)

After I click login a pop up appears, I can login correctly but in the console I get the error 

Refused to display 'https://login.microsoftonline.com/te/inverblock.onmicrosoft.com/b2c_1_signupin/oauth2/v2.0/authorize?response_type=token&scope=https%3A%2F%2Finverblock.onmicrosoft.com%2Finverblockapi%2Fread%20openid%20profile&client_id=b37e6ae9-98f3-4051-96c1-5a0d0678b82a&redirect_uri=https%3A%2F%2Flocalhost%3A3000%2F&state=1a636580-24a2-4665-9a45-bafebca082a1&nonce=d0fc2e91-36e5-4303-84e6-e943c15ef1e7&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.1.1&client-request-id=0f7b261a-879a-4414-bc1d-48ed0f21423e&prompt=none&domain_req=844f1a88-bc98-4dc0-86ca-f44adfb8a907&login_req=40e7eef7-66f6-48fe-82b0-67676ab43a60-b2c_1_signupin&domain_hint=organizations' in a frame because it set 'X-Frame-Options' to 'deny'.

When navigating to the URL I get the following error:

Correlation ID: f99221f2-95e9-47fa-83d0-8ad0daa4cf3e
Timestamp: 2017-10-21 03:46:30Z
AADB2C90205: This application does not have sufficient permissions against this web resource to perform the operation.

Here's my current configuration.

API Configuration

![image](https://user-images.githubusercontent.com/10178745/31847866-aa21fb14-b5e9-11e7-81b6-469c005b7d1a.png)

API Pusblished Scopes

![image](https://user-images.githubusercontent.com/10178745/31847869-c025dda4-b5e9-11e7-847b-26069d20a34f.png)

Client Web App Configuration

![image](https://user-images.githubusercontent.com/10178745/31847850-4edf6962-b5e9-11e7-8263-87043f09e786.png)

Client Web App Granted Scopes

![image](https://user-images.githubusercontent.com/10178745/31847854-648364ee-b5e9-11e7-816f-7b80377b2377.png)

I've spent too many hours trying to get this right. I really hope someone can help.

Best Regards

**Comment by huizarmx** [comment]
Hello again @SaeedAkhter-MSFT

I'm sorry, just after I reviewed my post asking for help I noticed that given that my UI in the portal is in spanish (I'm in Mexico) the columns in the table of the published scopes of the API are inverted and really the translation is bad, it should read "Valor del ámbito" instead of "Ámbito" and "Nombre del Ámbito" instead of "Descripción". Those labels in spanish are really confusing.

After typing the information in the right place everything else worked. Thanks anyway for all this thread. It's been very helpful.

BR

**Comment by kenturley** [comment]
I got the same error "application does not have sufficient permissions against this web resource." Mine was a simple mistake. I missed a detail in Step 5 of the tutorial for setting b2cScopes in the SPA's index.html. I needed to replace "demoapi" with "hello."

![demoapp](https://user-images.githubusercontent.com/1234883/32969888-f76072e6-cba3-11e7-8989-6d5f09d31099.jpg)

![demoapp1](https://user-images.githubusercontent.com/1234883/32970067-a624d74a-cba4-11e7-8152-5de92e615869.jpg)

**Comment by unoti** [comment]
I had the same problem "application does not have sufficient permissions against this web resource", Here is how I fixed it:

Go into the tenant, select Azure AD B2C on the left side of the portal.  On the left side click API Access.

![image](https://user-images.githubusercontent.com/5296180/33529238-c6efde54-d822-11e7-8465-e9d4103f9538.png)

Click + Add.

Select the API, from the first dropdown. Then select demo.read from the second dropdown.  Then click OK at the bottom.

![image](https://user-images.githubusercontent.com/5296180/33529243-e4db7d56-d822-11e7-8e47-05205430de8e.png)

After that, it worked.

There are many steps involved in the setup, many opportunities to do things wrong, and when something goes wrong it's hard (impossible?) to tell what went wrong where.  The documentation all refers to other pieces of documentation, so it's extremely difficult to just set this up and see it work with your own tenant.

**Comment by maslunde** [comment]
I also had the same problem. Spent many hours to find out. I find it very frustrating to work with Azure B2C as a developer due to lack of good documentation, updated documentation and well proved examples. When something break you almost have to be the creator of B2C to find out. Hopefully it will be a much better product in the future. Not to forget the naming convention Microsoft have done. It's a complete shitshow and differs all over. Ok, frustration passed for now. 

I had forgot to add the scope /demo.read after /demoapi
![error](https://user-images.githubusercontent.com/31503447/34433098-0af410ca-ec7d-11e7-915b-67749670cf4f.png)

Tbo I still don't understand the effect of having this scope after /demoapi, I guess that could be better explained as well together with rest of the settings that have to be provided.

**Comment by ahenaol** [comment]
Try editing your policy. Under **Token, session & SSO config**, change any value and save the changes. I think it is a AD B2C bug.

**Comment by kaburkett** [comment]
Linking a bug that was opened on the document side that seems to reference this issue.

**Comment by sameerag** [comment]
Is this still an issue with the latest sample? Please let us know.

**Comment by mikelazell** [comment]
> Is this still an issue with the latest sample? Please let us know.

Yes it is. I just had the same issue as people above. My config was correct. 

To fix I made a simple change to my signin flow (changed Refresh token lifetime (days) from 14 to 15) and back again and it all started working without any other changes..

**Comment by mikebridge** [comment]
I wasn't able to retrieve access tokens until I used @unoti's solution.  Wish I'd found that about 8 hours ago---I didn't see that step in any of the documentation.

**Comment by derisen** [comment]
The sample and the documentation has been recently updated. This issue is resolved now.
